image: java:17-jdk

stages:
  - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export JAVA_HOME=/home/sdks/zulu-17

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - .kotlin

build_kotlin:
  stage: build
  script:
    - ./gradlew clean publish --no-daemon
  only:
    - master
  tags:
    - linux

build_python:
  stage: build
  script:
    - cd python/
    - ./build.sh
    - python3 -m twine upload --repository gitlab dist/*
  only:
    - master
  tags:
    - linux