image: java:17-jdk
stages:
  - build
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export JAVA_HOME=/home/sdks/zulu-17
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - .kotlin
build:
  stage: build
  script:
    - ./gradlew generateKotlinGrammarSource publish --no-daemon
  only:
    - master
  tags:
    - linux

